# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Starter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Starter
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Fabric', '~> 1.7.5'
  pod 'Crashlytics', '~> 3.10.1'

#   target 'Starter-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'StarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Starter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Starter-tvOS

  target 'Starter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
